# -*- coding: utf-8 -*-
"""GS - PCAP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0EkRIAVbcJ2_ZOaRbW0iN4mpMN-xuKJ
"""

"""
FIAP - Global Solution 2026.1
Disciplina: Pensamento Computacional e Automação com Python
Projeto: Mission Control AI - Sistema Inteligente de Monitoramento de Missão Espacial

Autores: [Seu Nome / Nomes da Equipe]
"""

# ==========================================
# CONFIGURAÇÕES DA MISSÃO E DADOS DE ENTRADA
# ==========================================

NOME_MISSAO = "Project Silver Eclipse"
NOME_EQUIPE = "Lunar Vanguard"

# Lista de áreas monitoradas correspondente às colunas da matriz
AREAS_MONITORADAS = [
    "Temperatura interna",
    "Comunicação com a base",
    "Sistema de energia",
    "Suporte de oxigênio",
    "Estabilidade operacional"
]

# Matriz principal: cada linha é um ciclo, colunas na ordem das AREAS_MONITORADAS
DADOS_MISSAO = [
    [24, 92, 88, 96, 90],  # Ciclo 1: Estável
    [27, 80, 72, 94, 85],  # Ciclo 2: Estável
    [31, 65, 58, 91, 70],  # Ciclo 3: Atenção (Temperatura)
    [36, 42, 38, 87, 55],  # Ciclo 4: Crítica (Vários desvios)
    [39, 28, 19, 78, 35],  # Ciclo 5: Crítica (Falha severa)
    [34, 55, 32, 82, 50]   # Ciclo 6: Atenção (Tentativa de recuperação)
]

# Códigos de cores ANSI para deixar o terminal visualmente limpo e profissional
RESET = "\033[0m"
BOLD = "\033[1m"
VERDE = "\033[92m"
AMARELO = "\033[33m"
VERMELHO = "\033[91m"
CIANO = "\033[96m"


# ==========================================
# FUNÇÕES DE ANÁLISE DE PARÂMETROS
# ==========================================

def analisar_temperatura(valor):
    """Analisa a temperatura e retorna (classificação, pontos, descrição)."""
    if valor < 18:
        return "ATENÇÃO", 1, "Temperatura baixa"
    elif 18 <= valor <= 30:
        return "NORMAL", 0, "Temperatura estável"
    elif 30 < valor <= 35:
        return "ATENÇÃO", 1, "Temperatura elevada"
    else:
        return "CRÍTICO", 2, "Risco de superaquecimento"


def analisar_comunicacao(valor):
    """Analisa a comunicação e retorna (classificação, pontos, descrição)."""
    if valor < 30:
        return "CRÍTICO", 2, "Comunicação com a base em nível crítico"
    elif 30 <= valor <= 59:
        return "ATENÇÃO", 1, "Comunicação instável"
    else:
        return "NORMAL", 0, "Comunicação estável"


def analisar_bateria(valor):
    """Analisa a bateria e retorna (classificação, pontos, descrição)."""
    if valor < 20:
        return "CRÍTICO", 2, "Bateria em nível crítico"
    elif 20 <= valor <= 49:
        return "ATENÇÃO", 1, "Bateria abaixo do recomendado"
    else:
        return "NORMAL", 0, "Energia estável"


def analisar_oxigenio(valor):
    """Analisa o oxigênio e retorna (classificação, pontos, descrição)."""
    if valor < 80:
        return "CRÍTICO", 2, "Oxigênio em nível crítico"
    elif 80 <= valor <= 89:
        return "ATENÇÃO", 1, "Oxigênio abaixo do ideal"
    else:
        return "NORMAL", 0, "Oxigênio adequado"


def analisar_estabilidade(valor):
    """Analisa a estabilidade operacional e retorna (classificação, pontos, descrição)."""
    if valor < 40:
        return "CRÍTICO", 2, "Estabilidade operacional crítica"
    elif 40 <= valor <= 69:
        return "ATENÇÃO", 1, "Estabilidade operacional reduzida"
    else:
        return "NORMAL", 0, "Estabilidade operacional adequada"


# ==========================================
# FUNÇÕES DE LÓGICA DO SISTEMA e SEU "PLUS"
# ==========================================

def classificar_ciclo(pontos_totais):
    """Classifica a situação do ciclo com base na pontuação acumulada."""
    if 0 <= pontos_totais <= 2:
        return f"{VERDE}{BOLD}MISSÃO ESTÁVEL{RESET}", "MISSÃO ESTÁVEL"
    elif 3 <= pontos_totais <= 5:
        return f"{AMARELO}{BOLD}MISSÃO EM ATENÇÃO{RESET}", "MISSÃO EM ATENÇÃO"
    else:
        return f"{VERMELHO}{BOLD}MISSÃO CRÍTICA{RESET}", "MISSÃO CRÍTICA"


def gerar_recomendacao(classificacoes):
    """Gera diretrizes automáticas baseadas nos status críticos encontrados."""
    recomendas = []
    if classificacoes[0] == "CRÍTICO":
        recomendas.append("Verificar controle térmico da missão.")
    if classificacoes[1] == "CRÍTICO":
        recomendas.append("Tentar restabelecer contato com a base.")
    if classificacoes[2] == "CRÍTICO":
        recomendas.append("Ativar modo de economia de energia.")
    if classificacoes[3] == "CRÍTICO":
        recomendas.append("Acionar protocolo de suporte à vida.")
    if classificacoes[4] == "CRÍTICO":
        recomendas.append("Reduzir operações não essenciais.")

    if recomendas:
        # Se houver mais de 2 itens críticos, sugere o protocolo de segurança master
        if len(recomendas) >= 3:
            return "Ativar modo de segurança e priorizar suporte à vida, energia e comunicação."
        return " ".join(recomendas)

    # Se não houver nada crítico, mas houver sistemas em atenção
    if "ATENÇÃO" in classificacoes:
        return "Monitorar sistemas em atenção e preparar plano de contingência."

    return "Manter operação normal e continuar monitoramento."


def analisar_tendencia(primeiro_risco, ultimo_risco):
    """Compara o risco do início e do fim da missão para determinar a tendência."""
    if ultimo_risco > primeiro_risco:
        return f"{VERMELHO}A missão apresentou tendência de piora.{RESET}"
    elif ultimo_risco < primeiro_risco:
        return f"{VERDE}A missão apresentou tendência de melhora.{RESET}"
    else:
        return f"{AMARELO}A missão permaneceu estável em relação ao início.{RESET}"


def colorir_status(status):
    """Apenas uma função auxiliar estética (Plus) para colorir as tags dos parâmetros."""
    if status == "NORMAL": return f"{VERDE}NORMAL{RESET}"
    if status == "ATENÇÃO": return f"{AMARELO}ATENÇÃO{RESET}"
    return f"{VERMELHO}CRÍTICO{RESET}"


# ==========================================
# CORE: PROCESSAMENTO E RELATÓRIO FINAL
# ==========================================

def executar_mission_control():
    print(f"\n{CIANO}============================================================{RESET}")
    print(f"{BOLD}                     MISSION CONTROL AI                      {RESET}")
    print(f"{CIANO}============================================================{RESET}")
    print(f"{BOLD}Missão:{RESET} {NOME_MISSAO}")
    print(f"{BOLD}Equipe:{RESET} {NOME_EQUIPE}")
    print(f"{BOLD}Quantidade de ciclos analisados:{RESET} {len(DADOS_MISSAO)}")
    print(f"{CIANO}============================================================{RESET}\n")

    # Inicialização de variáveis para o relatório final
    somas_areas = [0, 0, 0, 0, 0]
    pontuacoes_ciclos = []
    total_ciclos_criticos = 0

    # Listas auxiliares para armazenar dados de cálculo das médias
    temp_lista, com_lista, bat_lista, ox_lista, est_lista = [], [], [], [], []

    # Loop principal (Estrutura de repetição exigida)
    for i, ciclo in enumerate(DADOS_MISSAO):
        num_ciclo = i + 1
        print(f"{BOLD}--- CICLO {num_ciclo} ---{RESET}")

        # Coleta dos dados brutos
        t, c, b, o, e = ciclo

        # Alimentando listas de médias
        temp_lista.append(t)
        com_lista.append(c)
        bat_lista.append(b)
        ox_lista.append(o)
        est_lista.append(e)

        # Executando as análises funcionais
        st_t, pt_t, desc_t = analisar_temperatura(t)
        st_c, pt_c, desc_c = analisar_comunicacao(c)
        st_b, pt_b, desc_b = analisar_bateria(b)
        st_o, pt_o, desc_o = analisar_oxigenio(o)
        st_e, pt_e, desc_e = analisar_estabilidade(e)

        # Acumulando riscos por área
        somas_areas[0] += pt_t
        somas_areas[1] += pt_c
        somas_areas[2] += pt_b
        somas_areas[3] += pt_o
        somas_areas[4] += pt_e

        # Exibição individual limpa no terminal
        print(f"Temperatura: {t}°C | {colorir_status(st_t)} | {desc_t}")
        print(f"Comunicação: {c}%  | {colorir_status(st_c)} | {desc_c}")
        print(f"Bateria:     {b}%  | {colorir_status(st_b)} | {desc_b}")
        print(f"Oxigênio:    {o}%  | {colorir_status(st_o)} | {desc_o}")
        print(f"Estabilidade:{e}%  | {colorir_status(st_e)} | {desc_e}")

        # Cálculos de pontuação e classificação do ciclo
        pontos_ciclo = pt_t + pt_c + pt_b + pt_o + pt_e
        pontuacoes_ciclos.append(pontos_cycle := pontos_ciclo)

        cor_classe, texto_classe = classificar_ciclo(pontos_ciclo)
        if texto_classe == "MISSÃO CRÍTICA":
            total_ciclos_criticos += 1

        recomendacao = gerar_recomendacao([st_t, st_c, st_b, st_o, st_e])

        print(f"Pontuação de risco do ciclo: {BOLD}{pontos_ciclo}{RESET}")
        print(f"Classificação do ciclo: {cor_classe}")
        print(f"Recomendação: {CIANO}{recomendacao}{RESET}")
        print("-" * 40)

    # Identificação do ciclo mais crítico e maior pontuação
    max_risco = max(pontuacoes_ciclos)
    indice_critico = pontuacoes_ciclos.index(max_risco) + 1
    risco_medio_total = sum(pontuacoes_ciclos) / len(DADOS_MISSAO)

    # Identificação da área mais afetada
    maior_risco_area = max(somas_areas)
    idx_area_afetada = somas_areas.index(maior_risco_area)
    area_mais_afetada = AREAS_MONITORADAS[idx_area_afetada]

    # Classificação final da missão baseada no risco médio
    _, classe_final = classificar_ciclo(int(risco_medio_total))

    # ==========================================
    # OUTPUT: RELATÓRIO FINAL DA MISSÃO
    # ==========================================
    print(f"\n{VERDE}============================================================{RESET}")
    print(f"{BOLD}                 RELATÓRIO FINAL DA MISSÃO                  {RESET}")
    print(f"{VERDE}============================================================{RESET}")
    print(f"{BOLD}Missão:{RESET} {NOME_MISSAO}  |  {BOLD}Equipe:{RESET} {NOME_EQUIPE}")
    print(f"{BOLD}Quantidade de ciclos analisados:{RESET} {len(DADOS_MISSAO)}\n")

    print(f"{BOLD}MÉDIAS DOS PARÂMETROS:{RESET}")
    print(f"Média de temperatura:  {sum(temp_lista)/len(temp_lista):.2f} °C")
    print(f"Média de comunicação:  {sum(com_lista)/len(com_lista):.2f}%")
    print(f"Média de bateria:      {sum(bat_lista)/len(bat_lista):.2f}%")
    print(f"Média de oxigênio:     {sum(ox_lista)/len(ox_lista):.2f}%")
    print(f"Média de estabilidade: {sum(est_lista)/len(est_lista):.2f}%\n")

    print(f"{BOLD}ANÁLISE DE INCIDENTES:{RESET}")
    print(f"Ciclo mais crítico:      Ciclo {indice_critico}")
    print(f"Maior pontuação de risco: {max_risco}")
    print(f"Risco médio da missão:    {risco_medio_total:.2f}")
    print(f"Quantidade de ciclos críticos: {total_ciclos_criticos}\n")

    print(f"{BOLD}TENDÊNCIA DA MISSÃO:{RESET}")
    print(analisar_tendencia(pontuacoes_ciclos[0], pontuacoes_ciclos[-1]))
    print()

    print(f"{BOLD}PONTUAÇÃO ACUMULADA POR ÁREA:{RESET}")
    for area, pontos in zip(AREAS_MONITORADAS, somas_areas):
        print(f"- {area}: {pontos} pontos")

    print(f"\n{BOLD}ÁREA MAIS AFETADA:{RESET}")
    print(f"{VERMELHO}{BOLD}{area_mais_afetada}{RESET}\n")

    print(f"{BOLD}CLASSIFICAÇÃO FINAL DA MISSÃO:{RESET}")
    cor_final, _ = classificar_ciclo(int(risco_medio_total))
    print(cor_final)
    print()

    print(f"{BOLD}CONCLUSÃO:{RESET}")
    if classe_final == "MISSÃO CRÍTICA":
        print(f"{VERMELHO}A missão enfrentou falhas severas intransponíveis. Protocolo de contingência total deve permanecer ativo.{RESET}")
    elif classe_final == "MISSÃO EM ATENÇÃO":
        print(f"{AMARELO}A operação registrou oscilações significativas ao longo dos ciclos analisados.\nMesmo com sinais de recuperação na última leitura, subsistemas ainda demandam cuidados e a equipe de engenharia deve preservar os protocolos de contingência ligados.{RESET}")
    else:
        print(f"{VERDE}Operação concluída com absoluto sucesso. Todos os sistemas principais se mantiveram dentro dos limites seguros na média histórica.{RESET}")
    print(f"{VERDE}============================================================{RESET}\n")


# Ponto de entrada que executa a aplicação
if __name__ == "__main__":
    executar_mission_control()